### ISSUE TITLE
Dimensions API request

### ISSUE THREAD

**Issue by jehrodrigues** [digital-science/dimensions-api-lab#10]
Hello,
 
I’m performing some requests in the Dimensions API (https://api-lab.dimensions.ai/index.html) and the performance is not what I expect in terms of requisition per minute.

I wanted to know whether there is a possibility to try out the API without a limit on the number of requests.
When I tried running the Dimensions concept extraction over a dataset, I keep getting "Too Many Requests for the Server. Sleeping for 30 seconds and then retrying."
 
It is possible to change this parameter?
 
Kind regards,

**Comment by eschares** [comment]
Hi Jessica,

I found a reference to a 30 query-per-minute API rate limit in the first bullet of this heading (https://api-lab.dimensions.ai/cookbooks/1-getting-started/1-Using-the-Dimcli-library-to-query-the-API.html#Iterative-querying-(loops)).

Thanks,
Eric

**Comment by lambdamusic** [comment]
That is correct, the Analytics API allows up to 30 requests per minute. 

See the official documentation page: https://docs.dimensions.ai/dsl/api.html
