### ISSUE TITLE
Error using query_iterative()

### ISSUE THREAD

**Issue by saurabh-khanna** [digital-science/dimensions-api-lab#17]
I am getting an error while iteratively querying data from the Dimensions API using `query_iterative()`. How do I fix this (as previous iterations succeed)?

Code:

```
query = """search publications where year in [2020] and category_for.name in ["4701 Communication and Media Studies", "3605 Screen and Digital Media"] return publications"""
df_result = dsl.query_iterative(query).as_dataframe()
```

Error:

<img width="918" alt="image" src="https://github.com/digital-science/dimensions-api-lab/assets/54084054/1f108e3d-728a-46ea-b3f6-852d0e3ff2d3">

**Comment by lambdamusic** [comment]
Query worked for me. 

Possibly a temporary server outage? 

![image](https://github.com/digital-science/dimensions-api-lab/assets/3493663/556f2877-f5df-4fe4-81bc-f2f35954c1c5)

If it happens again, the error message you got has instructions on how to deal with this e.g. `limit` and `force=True` - see also https://digital-science.github.io/dimcli/modules.html#dimcli.core.api.Dsl.query_iterative
