### ISSUE TITLE
ModuleNotFoundError: No module named 'dimcli'

### ISSUE THREAD

**Issue by nranthony** [digital-science/dimensions-api-lab#6]
Hi all.
Alas, I'm getting a ModuleNotFoundError: No module named 'dimcli' when running things from the colab links.  Am I missing something?
Thanks in advance for your time.
Neil

**Comment by lambdamusic** [comment]
Hi Neil what notebook are you trying to use? `dimcli` needs to be installed with this command `pip install -U dimcli` .. normally that's included in the notebooks but we may have missed it somewhere.

**Comment by nranthony** [comment]
Hi,
From the dimensions-api-lab page I click on the Colab icon.  It pops up notebook options.  I select the first option:  https://colab.research.google.com/github/digital-science/dimensions-api-lab/blob/master/archive/2019-04-Technical-University-of-Denmark/1-Exploring-the-DSL.ipynb
And then when I run the first line `from dimcli.shortcuts import dslquery_json as dslquery` it displays the error.
I just tried a bunch of the other notebooks listed and they all appear to have the same module error (I tried the first four or five down the list).
Thanks
Neil

**Comment by lambdamusic** [comment]
Please navigate to the `cookbook` folder and use the notebooks you can find there. Or simply go to https://digital-science.github.io/dimensions-api-lab/ which is a web portal rendering those cookbooks (e.g. [Exploring the DSL](https://digital-science.github.io/dimensions-api-lab/cookbooks/1-getting-started/2-Understanding-query-results.html)).

PS 
The notebooks in the `archive` folder are historical copies of past events and workshops that are not being maintained anymore and in many cases will not work 'out of the box'. We keep them simply for record purposes.
