### ISSUE TITLE
Link to cookbooks wrong?

### ISSUE THREAD

**Issue by saschamarkus-uberresearch** [digital-science/dimensions-api-lab#7]
The link in the Readme pointing to the cookbooks doesn't work if you're not logged in with a DS account.

While the repo is accessible without being logged in the link https://github.com/digital-science/dsl_lab_dev/tree/master/cookbooks doesn't work if you're not logged in or logged in with an account ouside of the DS organization.

But there is also a cookbooks folder in this repo.

**Comment by lambdamusic** [comment]
Thanks, I fixed the links
